### PR TITLE
Spanish translation for g0v manifesto

### PR DESCRIPTION
**Pull request by pr3ssh**
Just a quick note: the translation is ready but the content is not shown on `/intl/en/manifesto/es/`. Maybe some config missing. Hope it helps.

### CODE REVIEW

**Comment by tedlu-tw** [comment]
Hi @pr3ssh ! Thanks for helping on the translation! Just a few edit suggestions and questions on the translated content of the g0v Manifesto. 

- Estamos en todas partes -> Estamos **de** todas partes
  As this part of the manifesto focuses on "we are from everywhere (to gather)" instead of "we are located everywhere", it might be better to use "de" instead of "en". 
- Nos reunimos con la esperanza de mejorar **la** la sociedad civil de Taiwan...
- contribuir con tu conocimientos y experiencias -> contribuir con tu conocimientos, **proyecto** y experiencias
  Part of the g0v contributing style includes "bring your project to collaborate", therefore "con tu proyecto" may be necessary as well. 
- ...una comunidad plicéntrica... -> ...una comunidad **policéntrica**...
- Con esta Manifiesto como consenso... -> Con esta **Manifestó** como **base del** consenso...
- ...está hecha de ests proyectos... -> ...está hecha de **estos** proyectos...
- Conectamos difetentes perfiles par amplificar nuestra fuerza colectiva. -> Conectamos **diferentes** perfiles **con varios profesiones** par amplificar nuestra fuerza colectiva.
- ...colaboramos y exploramos nuevas fronteras. -> ...colaboramos y exploramos **fronteras nuevas**.
- Dónde estás tú -> **Somos tú**

As I'm not a native Spanish user, further confirmation of suggestion should be made before direct editing. Thanks!

**Review by tedlu-tw — APPROVED** [review]
Hi @pr3ssh! Thanks for providing the updated commit after the comment. I have reviewed the translation and the content seems great! Will merge directly as it LGTM. Thanks again for contributing.

**Comment by tedlu-tw** [comment]
Hi @pr3ssh, while trying to merge the pull request, I have noticed a conflict that has to be resolved. Can you fix this for me? Thanks.

**Comment by pr3ssh** [comment]
@tedlu-tw sorry for the delay in responding you. Due all conflicts, I would prefer to close this PR and creates a new and clean one.

**Pull request closed without merging**
